画面推移図作成
koga-ayako/my-graduation-website pull request #2
Opened 2024-12-15 02:06 UTC by ponpon29

### 画面遷移図
Figma：https://www.figma.com/design/sTLHwjeooCMRvXztN4eNua/%E7%84%A1%E9%A1%8C?node-id=0-1&p=f&t=zPithJcm4gVB4bON-0

### READMEに記載した機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] パスワード変更機能
- [x] ラーメン店検索機能
- [x] 投稿機能（画像投稿含む）
- [x] みんなの投稿閲覧機能（未ログインでも閲覧可能）
- [x] お気に入り機能

### 未ログインでも閲覧または利用できるページ
以下の項目は適切に未ログインでも閲覧または利用できる画面遷移になっているか？
- [x] 投稿閲覧機能
- [x] ラーメン店検索機能

### メールアドレス・パスワード変更確認項目
直接変更できるものではなく、一旦メールなどを介して専用のページで変更する画面遷移になっているか？
- [x] パスワード

### 各画面の作り込み
画面遷移だけでなく、必要なボタンやフォームが確認できるくらい作り込めているか？
- [x] 作り込みはある程度完了している（Figmaを見て画面の作成ができる状態にある）

2024-12-15 08:47 UTC, murata0705 commented
@ponpon29 
figma のデザインに閲覧制限がかかっているみたいなので修正お願いできますか。

2024-12-15 08:48 UTC, tarakish requested changes
figmaにアクセスしましたが権限がなく閲覧ができなかったため、権限の見直しをお願いします！
![スクリーンショット 2024-12-15 17 47 25](https://github.com/user-attachments/assets/0ac1347e-6d91-499a-95b8-2083071faf58)

2024-12-15 12:07 UTC, ponpon29 commented
申し訳ございません。修正いたしました。確認よろしくお願いいたします。

2024-12-16 04:56 UTC, TakenakaEri commented
LGTMです！

この後、アプリを作成していくにあたり、変更点が出てくるとは思いますが、適時ご自身の判断で修正していただいて問題ありません。

次の課題も頑張ってください！

2024-12-18 15:57 UTC, merged